
# GitHub Actions Workflow for MLOps Pipeline
name: Tourism Project Pipeline

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main  # Automatically triggers on push 

jobs:
  # Job for registering dataset
  register-dataset: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r deployment/requirements.txt
      # Upload dataset to HF space
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Python script for registering dataset 
        run: python model_building/data_register.py

  # Job for data preparation
  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r deployment/requirements.txt
      # Prepare data and upload to HF space
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Python script for preparing and 
        # uploading the prepared dataset
        run: python model_building/prep.py

  # Job for model training
  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r deployment/requirements.txt
      # Start MLflow Server
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &  # Run MLflow UI in the background
          sleep 5  # Wait for a moment to let the server starts
      # Build models and upload best model to HF space
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Python script for ML experimentation and uploading the best model 
        run: python model_building/experimentation.py

  # Job for streamlit app deployment 
  deploy-hosting:
    runs-on: ubuntu-latest
    needs: model-training
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r deployment/requirements.txt
      # Push deployment files to HF space
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Python script for uploading the streamlit app to HF space
        run: python hosting/hosting.py
